<?php
include_once ("lang/lang_default.php");
include ("includes/dbconnection.php");
include_once ("includes/login.php");
include_once ("includes/session_store.php");


$sql_query = 'SELECT id_user, `login_username`, `login_password` FROM `login_user` WHERE id_user';
$data = mysqli_query($con, $sql_query);
$row = mysqli_fetch_array($data);
echo "<!DOCTYPE html>";
echo "<html>";
	echo "<head>";
		echo "<meta charset='UTF-8'>";
		echo "<title>".$Lang['auth_title']."</title>";
		echo "<link href='css/style.css' rel='stylesheet' type='text/css'>";
		echo "<link href='css/media.css' rel='stylesheet' type='text/css'>";
		echo "<link rel='icon' type='image/png' href='favicon.png'";
		echo "<link href='//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' rel='stylesheet' type='text/css'>";
		echo "<link href='//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css' rel='stylesheet' id='bootstrap-css'>";
		echo "<script src='//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>";
		echo "<script src='//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js'></script>";
		echo "<script src='js/main.js' type='text/javascript' ></script>";
	echo "</head>";
	
	echo "<body>";
		echo "<div class='language_block'>";
			echo "<div class='container'>";
				echo "<div class='row'>";		
					echo "<div class='copy-text'>";
						echo "<div class='lang text-left' name='lang'>";
							echo "<a href='main.php?lang=ru'><img src='img/ru.png'></a>";
							echo "<a href='main.php?lang=en'><img src='img/en.png'></a>";
						echo "</div>";
					echo "</div>";
				echo "</div>";
			echo "</div>";
		echo "</div>";
		echo "<div class='login_form'>";
			echo "<div class='container'>";
				echo "<div class='row'>";
					echo "<div class='col-xl-4 login_text'>";
						echo "<h2 class='text-center'>".$Lang['name_head']."</h2>";
						echo "<form class='form' method='post' action='main.php?lang=".$Lang['lang']."'>";
							echo "<div class='form_group'>";
								echo "<label for='inputUser' class='text-uppercase'>".$Lang['name_user']."</label>";
								echo "<input id='login' type='text' name='inputUser' class='form_control' placeholder='' required autocomplete='off'>";
							echo "</div>";
							echo "<div class='form_group'>";
								echo "<label for='inputPassword' class='text-uppercase'>".$Lang['name_password']."</label>";
								echo "<input id='pass' type='password' name='inputPassword' class='form_control' placeholder='' required autocomplete='off'>";
							echo "</div>";
							echo "<div class='hidden'>";
							    echo "<input type='hidden' name='id' class='form-control' value=".$row['id_user'].">";
							echo "</div>";
							echo "<div class='form_check'>";
								echo "<label class='form_check_label'>";
									echo "<small id='errors'>".$_SESSION['Message']."</small>";
								echo "</label>";
								echo "<button name='submit' type='submit' class='btn btn_login float-right'>".$Lang['name_submit']."</button>";
							echo "</div>";
						echo "</form>";
						echo "<div class='form_check'>";
							echo "<label>";
								echo "<span>".$Lang['text_register'].  " <a href='register.php?lang=".$Lang['lang']."'>".$Lang['name_register']."</a></span>";
							echo "</label>";
						echo "</div>";
					echo "</div>";
					echo "<div class='col-xl-8 banner_sec'>";
						echo "<div id='carouselExampleIndicators' class='carousel slide' data-ride='carousel'>";
							echo "<ol class='carousel-indicators'>";
								echo "<li data-target='#carouselExampleIndicators' data-slide-to='0' class='active'></li>";
								echo "<li data-target='#carouselExampleIndicators' data-slide-to='1'></li>";
								echo "<li data-target='#carouselExampleIndicators' data-slide-to='2'></li>";
							echo "</ol>";
							echo "<div class='carousel-inner' role='listbox'>";
								echo "<div class='carousel-item active'>";
									echo "<img class='d-block img-fluid' src='img/pexels-photo.jpg' alt='First slide'>";
								echo "</div>";
								echo "<div class='carousel-item'>";
									echo "<img class='d-block img-fluid' src='img/people-coffee-tea-meeting.jpg' alt='First slide'>";
								echo "</div>";
								echo "<div class='carousel-item'>";
									echo "<img class='d-block img-fluid' src='img/pexels-photo-872957.jpeg' alt='First slide'>";
								echo "</div>";
							echo "</div>";
						echo "</div>";
					echo "</div>";
				echo "</div>";
			echo "</div>";
		echo "</div>";
	echo "</body>";
echo "</html>";
?>
